AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
Metrics/LineLength:
  Max: 120
  Severity: refactor
Metrics/ClassLength:
  Max: 175
  Severity: refactor
Metrics/AbcSize:
  Max: 300
Metrics/MethodLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
